### ISSUE TITLE
Reduce minimum required dart version

### ISSUE THREAD

**Issue by Chiggy-Playz** [flutter-cavalry/saf_stream#2]
The package current needs flutter 3.24.3 which is latest at the moment of writing, but the plugin doesn't use any dart or flutter feature that it needs 3.24.3 as the minimum version. Same goes for the `saf_util` package. Can it be lowered so we can use it in our project?

**Comment by mgenware** [comment]
@Chiggy-Playz 

The pubspec.yaml has the following version requirements:
```yaml
environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=2.5.0"
```

Where did you find the `flutter 3.24.3` requirement?
